import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import {Noto_Kufi_Arabic} from "next/font/google"
import { Almarai } from "next/font/google";
import Nabar from "./Navigation/Nabar";
import Sidebar from "./Navigation/Sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import Shadsidebar from "./Navigation/Shadsidebar";
import ResponsiveSidebar from "./Navigation/ResponsiveSidebar";
// import { AppSidebar } from "@/components/app-sidebar"
// const KufiArabic=Noto_Kufi_Arabic({subsets:["arabic"],weight:["300","400","700","800"]})
const Almarai=Noto_Kufi_Arabic({subsets:["arabic"],weight:["300","400","700","800"]})
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body  className={Almarai.className} >
         <header>
        <Nabar></Nabar>
      </header>
      <main dir="rtl">
        <Sidebar></Sidebar>
        {/* <ResponsiveSidebar/> */}

        
        <section className="PageMainSection">
        {children}
        </section>
      </main>
       
      </body>
    </html>
  );
}
